In [2]:
import pandas as pd
df = pd.read_csv('csv_file.csv')
avg_salary = df['Salary'].mean()
high_earners = df[df['Salary']>avg_salary]
high_earners

              Name  Age   Department  Salary
0         John Doe   28  Engineering   75000
1       Jane Smith   34    Marketing   82000
3      Emily Davis   30  Engineering   79000
5    Sarah Johnson   31    Marketing   81000
7   Jessica Taylor   29  Engineering   77000
9     Laura Martin   33    Marketing   85000
10   Robert Harris   42  Engineering   90000
12     Kevin Lewis   35  Engineering   83000
14    James Walker   38    Marketing   88000
16   William Young   39  Engineering   86000
17  Jennifer Allen   31    Marketing   79000

there are  11 employees earning above the average salary

In [3]:
df[(df['Department'] == 'Engineering')&(df['Salary']>avg_salary)]

              Name  Age   Department  Salary
0         John Doe   28  Engineering   75000
3      Emily Davis   30  Engineering   79000
7   Jessica Taylor   29  Engineering   77000
10   Robert Harris   42  Engineering   90000
12     Kevin Lewis   35  Engineering   83000
16   William Young   39  Engineering   86000

6 Engineering employees earn above the overall average salary

In [4]:
df[(df['Age']>40)&(df['Salary']>avg_salary)]

             Name  Age   Department  Salary
10  Robert Harris   42  Engineering   90000

Senior employees do not tend to earn above average salary.

1.Do conditions feel clearer than before?
yes
2.Did Python logic feel less scary?
not more
3.Where did you pause to think?
not yet